task: abiomed
algo-name: mbpo_kde_acp
reward-penalty-coef: 0.01
seed: 1
noise_rate: 0.0
noise_scale: 0.0
gamma1: 0.2
gamma2: 0.8
gamma3: 0.0
epoch: 110
penalty_type: "linear"
classifier_model_name: abiomed/trained_kde_abiomed