task: abiomed
algo-name: mbpo
reward-penalty-coef: 0.0
seed: 1
data_path: "/abiomed/offline_datasets/SAC_5000eps_stochastic.npz"
noise_rate: 0.0
noise_scale: 0.0
gamma1: 0.0
gamma2: 0.0
gamma3: 0.0
epoch: 80
