task: abiomed
algo-name: mbpo_kde_ws_acp_tanh
reward-penalty-coef: 1
seed: 1
noise_rate: 0.0
noise_scale: 0.0
gamma1: 0.0
gamma2: 0.0
gamma3: 0.0
epoch: 100
penalty_type: "tanh"
classifier_model_name: abiomed/trained_kde_abiomed