task: abiomed
algo-name: mbpo_kde_ws
reward-penalty-coef: 0.005
seed: 1
noise_rate: 0.0
noise_scale: 0.0
gamma1: 0.0
gamma2: 0.8
gamma3: 0.0
epoch: 110
penalty_type: "inverse"
classifier_model_name: abiomed/trained_kde_abiomed