task: abiomed
algo-name: bcq
seed: 1
data_path: "/abiomed/offline_datasets/SAC_exp_5000eps_stochastic_noise0.80_scale0.20.npz"
noise_rate: 0.8
noise_scale: 0.2
gamma1: 0.0
gamma2: 0.0
gamma3: 0.0
max_timesteps: 200000
