task: abiomed
algo-name: mopo_shaped
reward-penalty-coef: 0.5
data_path: "/abiomed/offline_datasets/SAC_exp_200000eps_stochastic_noise0.80_scale0.20.npz"
seed: 1
noise_rate: 0.8
noise_scale: 0.2
gamma1: 0.0
gamma2: 0.5
gamma3: 0.0
epoch: 100
